name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: testing jfaden.net server ssh connection
      uses: appleboy/ssh-action@master
      with:
        host: jfaden.net
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.OMG_SECRET }}
        port: 887
        script: |
          echo $HOSTNAME
          cd /var/www/cottagesystems.com/autoplot/git/server-java
          git pull origin main
          git status
          cd HapiServer
          ant dist
          cp dist/HapiServer.war /home/jbf/public_html/autoplot/study/jeremy/2022/20220427/
          echo "see https://cottagesystems.com/autoplot/git/server-java/HapiServer/dist/HapiServer.war"
          
